'use client'

import { useState } from 'react'
import { useTemplateClipUrl } from './templateClipUrl'

// A looping clip of the template's real render, served from the public Supabase
// bucket and regenerated by `npm run previews`. This is the faithful-but-cheap
// preview: it IS the actual output, muted and looping, with no engine coupling
// and one <video> per card. Until a clip exists for a template, the card's
// gradient backdrop simply shows through.

export function TemplatePreviewVideo({ id }: { id: string }) {
  const [ok, setOk] = useState(true)
  const src = useTemplateClipUrl(id)
  if (!src || !ok) return null
  return (
    <video
      src={src}
      autoPlay
      loop
      muted
      playsInline
      preload="metadata"
      onError={() => setOk(false)}
      className="absolute inset-0 h-full w-full object-cover"
    />
  )
}
