import { useEffect, useMemo, useRef } from 'react'
import { Mesh, MeshPhysicalMaterial, type IUniform } from 'three'
import { useInstrumentFrame } from '../core/visual/instrumentFrame'
import {
  FUNDAMENTAL_GEOMETRIES,
  FundamentalGeometryShape,
  normalizeFundamentalGeometry,
  type FundamentalGeometryId,
} from './FundamentalGeometry'
import { KALEIDO_FIELD_GLSL } from '../effects/materials/kaleidoField'
import { barrelTwist } from './kaleidoTwist'
import { paramDefault, type ObjectInstrumentDef } from './types'

/**
 * Kaleido Solid: a solid whose SURFACE is a live kaleidoscope.
 *
 * The pattern is generated in OBJECT space, so it is bolted to the surface -
 * it turns and travels with the mesh instead of sliding across it as the object
 * moves. Object space rather than UV space on purpose: a cube's UV seams would
 * tear the pattern into six unrelated tiles, and object space has no seams at
 * all, so one field works for every solid in the vocabulary.
 *
 * Nothing here is a preset or a baked image. The shards continuously grow and
 * shrink, drift within their cells, morph between 3 and 7 sides, and each one
 * cycles its own hue - so the surface never settles into a fixed texture.
 *
 * The field is injected into a MeshPhysicalMaterial rather than drawn with a raw
 * ShaderMaterial, so the scene's real lights, clearcoat and shadows still model
 * the form; the kaleidoscope supplies base colour and tints the emissive glow.
 */

/** Sphere shows the mandala most clearly, so it is the shape the instrument
 *  arrives as. Must match the `geometry` param default below AND the initial
 *  `visible` flag on the meshes. */
const DEFAULT_GEOMETRY: FundamentalGeometryId = 'sphere'

export const kaleidoSolidInstrument: ObjectInstrumentDef = {
  id: 'kaleidoSolid',
  name: 'Kaleido Solid',
  kind: 'object',
  userInterfaceRenderer: 'kaleidoSolid',
  // Position and size are the canonical track transform (core/transform.ts), so
  // these are behaviour only. Four knobs on purpose - everything else that makes
  // the surface live is derived in the shader.
  params: [
    { key: 'geometry', label: 'Geometry', type: 'string', default: DEFAULT_GEOMETRY },
    // Floored in the shader: automation lanes interpolate continuously and a
    // fractional wedge count tears the fold at the wrap seam.
    { key: 'facets', label: 'Facets', min: 2, max: 16, step: 1, default: 6 },
    { key: 'scale', label: 'Scale', min: 0.3, max: 3, step: 0.05, default: 1 },
    { key: 'drift', label: 'Drift', min: 0, max: 2, step: 0.05, default: 0.6 },
    { key: 'hue', label: 'Hue', min: 0, max: 6.28, step: 0.05, default: 0 },
  ],
  // A note flicks the kaleidoscope's barrel: the pattern lurches to a new
  // arrangement and settles. Pitch picks the coarse size of the flick.
  midiRows: [
    { pitch: 76, label: 'Twist · hard', emphasized: true },
    { pitch: 68, label: 'Twist · strong' },
    { pitch: 60, label: 'Twist · medium' },
    { pitch: 52, label: 'Twist · soft' },
    { pitch: 44, label: 'Twist · nudge' },
  ],
  component: KaleidoSolid,
}

/** One solid per track, its surface generated by KALEIDO_FIELD_GLSL. */
export function KaleidoSolid({ trackId }: { trackId: string }) {
  const meshRefs = useRef<Partial<Record<FundamentalGeometryId, Mesh | null>>>({})

  // One uniform object set, shared by the single material below. Mutating
  // `.value` per frame never triggers a React render, per the engine's rule.
  const uniforms = useRef<Record<string, IUniform>>({
    uKBeat: { value: 0 },
    uKFacets: { value: paramDefault(kaleidoSolidInstrument, 'facets') },
    uKScale: { value: paramDefault(kaleidoSolidInstrument, 'scale') },
    uKDrift: { value: paramDefault(kaleidoSolidInstrument, 'drift') },
    uKHue: { value: paramDefault(kaleidoSolidInstrument, 'hue') },
    uKTwist: { value: 0 },
  })

  // One material for all six meshes (only one is ever visible), so switching
  // geometry cannot switch appearance.
  const material = useMemo(() => {
    const mat = new MeshPhysicalMaterial({
      color: '#ffffff',
      metalness: 0.05,
      roughness: 0.46,
      // Kept low deliberately: the field already supplies vivid colour, and a
      // strong clearcoat/emissive on top clips the lit side and the grazing rim
      // to white, which reads as a blown-out blob rather than glass.
      clearcoat: 0.3,
      clearcoatRoughness: 0.3,
      envMapIntensity: 0.7,
      emissive: '#ffffff',
      emissiveIntensity: 0.16,
    })
    mat.onBeforeCompile = (shader) => {
      Object.assign(shader.uniforms, uniforms.current)
      shader.vertexShader = shader.vertexShader
        .replace('#include <common>', '#include <common>\nvarying vec3 vKObj;')
        // begin_vertex is where `transformed` is seeded from `position`, i.e. the
        // last point at which position is still in the solid's own space.
        .replace('#include <begin_vertex>', '#include <begin_vertex>\n  vKObj = position;')
      shader.fragmentShader = shader.fragmentShader
        .replace('#include <common>', `#include <common>\nvarying vec3 vKObj;\n${KALEIDO_FIELD_GLSL}`)
        .replace(
          'vec4 diffuseColor = vec4( diffuse, opacity );',
          // Scaled to leave the lights headroom: the field peaks near 1.0, and a
          // near-white albedo under this scene's ambient + directional + two point
          // lights saturates the lit hemisphere to pale wash. Albedo is a
          // REFLECTANCE, so it belongs well below 1.
          'vec3 kSurf = kaleidoField(vKObj);\n  vec4 diffuseColor = vec4( kSurf * 0.5, opacity );',
        )
        // `emissive` already carries emissiveIntensity, so tinting it by the field
        // makes the glow follow the shards instead of washing them flat white.
        .replace('vec3 totalEmissiveRadiance = emissive;', 'vec3 totalEmissiveRadiance = emissive * kSurf;')
    }
    return mat
  }, [])

  useEffect(() => () => { material.dispose() }, [material])

  useInstrumentFrame(trackId, (state) => {
    // Tracks are created without stringParams populated, so an unset value must
    // fall back to THIS instrument's default. normalizeFundamentalGeometry's own
    // fallback is 'cube' (right for the 3D Shape instrument, wrong here), which
    // otherwise silently renders a cube while the panel reports a sphere.
    const geometry = normalizeFundamentalGeometry(state.stringParams.geometry ?? DEFAULT_GEOMETRY)
    const mesh = meshRefs.current[geometry]
    // Bail rather than half-update: a silent partial pass would leave the solid
    // stale until the next input change, which may never come while paused.
    if (!mesh) return false
    for (const option of FUNDAMENTAL_GEOMETRIES) {
      const candidate = meshRefs.current[option.id]
      if (candidate) candidate.visible = option.id === geometry
    }

    const u = uniforms.current
    u.uKBeat.value = state.beat
    u.uKFacets.value = state.params.facets ?? paramDefault(kaleidoSolidInstrument, 'facets')
    u.uKScale.value = state.params.scale ?? paramDefault(kaleidoSolidInstrument, 'scale')
    u.uKDrift.value = state.params.drift ?? paramDefault(kaleidoSolidInstrument, 'drift')
    u.uKHue.value = state.params.hue ?? paramDefault(kaleidoSolidInstrument, 'hue')
    u.uKTwist.value = barrelTwist(state.notes, state.beat)
  })

  return (
    <group>
      {FUNDAMENTAL_GEOMETRIES.map(({ id }) => (
        <mesh
          key={id}
          ref={(el) => { meshRefs.current[id] = el }}
          visible={id === DEFAULT_GEOMETRY}
          material={material}
          castShadow
          receiveShadow
        >
          <FundamentalGeometryShape geometry={id} />
        </mesh>
      ))}
    </group>
  )
}
