// GENERATED by scripts/code-instruments.cjs - do not edit by hand.
// Every file under instruments/custom/ that exports `instrument` or
// `composition` is listed here; add a file and it is registered.

import type { CodeCompositionDef } from '../code/composition'
import { composition as c0 } from './innuendo/portal'

export const CODE_COMPOSITIONS: CodeCompositionDef[] = [c0]

const packs: string[] = ["innuendo"]

/** def id → pack (its folder under instruments/custom/). */
export const CODE_COMPOSITIONS_PACKS: Record<string, string> = Object.fromEntries(CODE_COMPOSITIONS.map((d, i) => [d.id, packs[i]]))
