// GENERATED by scripts/code-instruments.cjs - do not edit by hand.
// Every file under instruments/custom/ that exports `instrument` or
// `composition` is listed here; add a file and it is registered.

import type { CodeInstrumentDef } from '../code/define'
import { instrument as c0 } from './core/lane'
import { instrument as c1 } from './examples/pulse-ring'
import { instrument as c2 } from './innuendo/blades'
import { instrument as c3 } from './innuendo/chladni'
import { instrument as c4 } from './innuendo/fifths'
import { instrument as c5 } from './innuendo/glyphs'
import { instrument as c6 } from './innuendo/hairline'
import { instrument as c7 } from './innuendo/mirror'
import { instrument as c8 } from './innuendo/orb'
import { instrument as c9 } from './innuendo/pen'
import { instrument as c10 } from './innuendo/rig'
import { instrument as c11 } from './innuendo/step-ring'
import { instrument as c12 } from './innuendo/tunnel'

export const CODE_INSTRUMENTS: CodeInstrumentDef[] = [c0, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12]

const packs: string[] = ["core","examples","innuendo","innuendo","innuendo","innuendo","innuendo","innuendo","innuendo","innuendo","innuendo","innuendo","innuendo"]

/** def id → pack (its folder under instruments/custom/). */
export const CODE_INSTRUMENTS_PACKS: Record<string, string> = Object.fromEntries(CODE_INSTRUMENTS.map((d, i) => [d.id, packs[i]]))
